pluginVersion=1.4.19
pluginSinceBuild=261
runIdeVersion=2026.1.3

org.jetbrains.intellij.platform.selfUpdateCheck=false
org.jetbrains.intellij.platform.useCacheRedirector=true
kotlin.stdlib.default.dependency=false

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.daemon.jvmargs=-Xmx4096m
org.gradle.warning.mode=all
