pluginVersion=1.4.18
pluginSinceBuild=243

runIdeVersion=2025.3
org.jetbrains.intellij.platform.selfUpdateCheck=false
org.jetbrains.intellij.platform.useCacheRedirector=false

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.warning.mode=all
kotlin.daemon.jvmargs=-Xmx4g
